# Generated by Django 3.1.2 on 2020-10-15 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100, validators=[django.core.validators.MinValueValidator(0, 'Please provide valid number')])),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
